/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'board-members': BoardMember;
    'management-team': ManagementTeam;
    'news-items': NewsItem;
    'training-programs': TrainingProgram;
    'job-openings': JobOpening;
    'case-studies': CaseStudy;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    'management-team': ManagementTeamSelect<false> | ManagementTeamSelect<true>;
    'news-items': NewsItemsSelect<false> | NewsItemsSelect<true>;
    'training-programs': TrainingProgramsSelect<false> | TrainingProgramsSelect<true>;
    'job-openings': JobOpeningsSelect<false> | JobOpeningsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    nav: Nav;
    footer: Footer;
    home: Home;
    'company-board-page': CompanyBoardPage;
    'company-management-page': CompanyManagementPage;
    'company-news-page': CompanyNewsPage;
    'company-training-page': CompanyTrainingPage;
    'career-current-openings-page': CareerCurrentOpeningsPage;
    'career-employee-benefits': CareerEmployeeBenefit;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'company-board-page': CompanyBoardPageSelect<false> | CompanyBoardPageSelect<true>;
    'company-management-page': CompanyManagementPageSelect<false> | CompanyManagementPageSelect<true>;
    'company-news-page': CompanyNewsPageSelect<false> | CompanyNewsPageSelect<true>;
    'company-training-page': CompanyTrainingPageSelect<false> | CompanyTrainingPageSelect<true>;
    'career-current-openings-page': CareerCurrentOpeningsPageSelect<false> | CareerCurrentOpeningsPageSelect<true>;
    'career-employee-benefits': CareerEmployeeBenefitsSelect<false> | CareerEmployeeBenefitsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for accessibility & SEO. Required.
   */
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Company > Board page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  photo: number | Media;
  name: string;
  title: string;
  bio: string;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Company > Management Team page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-team".
 */
export interface ManagementTeam {
  id: number;
  photo: number | Media;
  name: string;
  title: string;
  bio?: string | null;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Company > News page. Category controls which section (Media Coverage / Industry Insights / Awards) it appears in. Toggle "Featured" to show it in the Featured News section at the top of the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items".
 */
export interface NewsItem {
  id: number;
  title: string;
  /**
   * Auto-filled from the title — leave blank and it fills itself in when you save. Used at /company/news/[slug].
   */
  slug?: string | null;
  category: 'media-coverage' | 'industry-insights' | 'awards';
  /**
   * Show this item in the "Featured News" section at the top of the News page.
   */
  featured?: boolean | null;
  publishedDate: string;
  /**
   * Short summary shown on the News list page and in card previews.
   */
  summary: string;
  /**
   * Full article body shown on the detail page. Optional — falls back to summary if empty.
   */
  content?: string | null;
  /**
   * Hero image used on the card and detail page.
   */
  image?: (number | null) | Media;
  /**
   * Optional. Paste a YouTube (or Vimeo) link — it will be embedded on the detail page.
   */
  videoUrl?: string | null;
  /**
   * Source name, e.g. Economic Times, Business Standard
   */
  source?: string | null;
  /**
   * Optional — powers the "About the Source" card in the detail page sidebar.
   */
  sourceDetails?: {
    /**
     * Small square logo. Falls back to initials if empty.
     */
    logo?: (number | null) | Media;
    /**
     * One or two line description of the publication.
     */
    description?: string | null;
    /**
     * e.g. https://economictimes.indiatimes.com
     */
    website?: string | null;
  };
  /**
   * Optional link to the full external article.
   */
  externalLink?: string | null;
  /**
   * Optional byline shown on the detail page.
   */
  author?: {
    name?: string | null;
    /**
     * e.g. Digital Strategy Lead, OneSIS
     */
    role?: string | null;
    image?: (number | null) | Media;
    /**
     * Full LinkedIn profile URL, optional.
     */
    linkedin?: string | null;
    /**
     * Short one to two line bio.
     */
    bio?: string | null;
  };
  /**
   * Estimated reading time in minutes, e.g. 4
   */
  readingTime?: number | null;
  /**
   * Optional highlighted quote block shown on the detail page.
   */
  quote?: {
    text?: string | null;
    /**
     * e.g. "OneSIS Leadership Team"
     */
    attribution?: string | null;
  };
  /**
   * Short bullet points shown in a "Key Takeaways" callout box (main column and sidebar).
   */
  keyTakeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Press enter after each tag. Shown as chips on the detail page.
   */
  tags?: string[] | null;
  /**
   * Pick up to 3 related articles to show at the bottom of this article.
   */
  relatedNews?: (number | NewsItem)[] | null;
  seo?: {
    /**
     * Falls back to Title if left empty.
     */
    metaTitle?: string | null;
    /**
     * Falls back to Summary if left empty.
     */
    metaDescription?: string | null;
    /**
     * Falls back to the hero Image if left empty.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Company > Training & Development page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-programs".
 */
export interface TrainingProgram {
  id: number;
  title: string;
  description: string;
  image: number | Media;
  /**
   * Lower numbers show first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Career > Current Openings page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings".
 */
export interface JobOpening {
  id: number;
  title: string;
  department: string;
  location: string;
  type: 'full-time' | 'part-time' | 'contract';
  /**
   * e.g. 5–8 yrs
   */
  experience?: string | null;
  description?: string | null;
  /**
   * Turn off to hide without deleting.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Solutions > Case Studies — listing cards and individual project detail pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  clientName?: string | null;
  location?: string | null;
  category: 'civil-interior' | 'property-management' | 'specialized-civil' | 'ifm-technical' | 'pmc';
  coverImage: number | Media;
  shortDescription?: string | null;
  featured?: boolean | null;
  sortOrder?: number | null;
  /**
   * Auto-filled from the title. You can also edit it manually. URL path: /solutions/case-studies/[slug]
   */
  slug?: string | null;
  projectOverview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  services?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  keyFigures?:
    | {
        /**
         * e.g. 22,77,219 Sqft
         */
        value: string;
        /**
         * e.g. Residential Building
         */
        label: string;
        id?: string | null;
      }[]
    | null;
  projectImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  projectType?: string | null;
  areaSize?: string | null;
  completionYear?: number | null;
  additionalDetails?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'management-team';
        value: number | ManagementTeam;
      } | null)
    | ({
        relationTo: 'news-items';
        value: number | NewsItem;
      } | null)
    | ({
        relationTo: 'training-programs';
        value: number | TrainingProgram;
      } | null)
    | ({
        relationTo: 'job-openings';
        value: number | JobOpening;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  photo?: T;
  name?: T;
  title?: T;
  bio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "management-team_select".
 */
export interface ManagementTeamSelect<T extends boolean = true> {
  photo?: T;
  name?: T;
  title?: T;
  bio?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-items_select".
 */
export interface NewsItemsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  featured?: T;
  publishedDate?: T;
  summary?: T;
  content?: T;
  image?: T;
  videoUrl?: T;
  source?: T;
  sourceDetails?:
    | T
    | {
        logo?: T;
        description?: T;
        website?: T;
      };
  externalLink?: T;
  author?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        linkedin?: T;
        bio?: T;
      };
  readingTime?: T;
  quote?:
    | T
    | {
        text?: T;
        attribution?: T;
      };
  keyTakeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  tags?: T;
  relatedNews?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-programs_select".
 */
export interface TrainingProgramsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-openings_select".
 */
export interface JobOpeningsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  location?: T;
  type?: T;
  experience?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  clientName?: T;
  location?: T;
  category?: T;
  coverImage?: T;
  shortDescription?: T;
  featured?: T;
  sortOrder?: T;
  slug?: T;
  projectOverview?: T;
  solution?: T;
  services?:
    | T
    | {
        label?: T;
        id?: T;
      };
  keyFigures?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  projectImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  projectType?: T;
  areaSize?: T;
  completionYear?: T;
  additionalDetails?: T;
  metaTitle?: T;
  metaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  logoText: string;
  logo?: (number | null) | Media;
  parentBadge?: string | null;
  ctaLabel?: string | null;
  links?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description: string;
  badge?: string | null;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  social?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  copyright: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    eyebrow: string;
    heading?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    headingAccent?: string | null;
    body: string;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    scrollLabel?: string | null;
    banner: number | Media;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  about: {
    eyebrow: string;
    heading?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    headingAccent?: string | null;
    body: string;
    badges?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    facts?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    image: number | Media;
    imageCaption?: string | null;
  };
  verticals: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    body?: string | null;
    items?:
      | {
          index: string;
          title: string;
          description: string;
          tags?:
            | {
                label: string;
                id?: string | null;
              }[]
            | null;
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  statsStrip?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  hardcoreRepair: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    body: string;
    sectorsHeading?: string | null;
    checklist?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    cta?: string | null;
    image: number | Media;
    imageCaption?: string | null;
    imageSubcaption?: string | null;
  };
  corporateInterior: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    sectorsHeading?: string | null;
    body: string;
    checklist?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    cta?: string | null;
    image: number | Media;
    imageCaption?: string | null;
    imageSubcaption?: string | null;
  };
  officeInterior: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    sectorsHeading?: string | null;
    body: string;
    checklist?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    cta?: string | null;
    image: number | Media;
    imageCaption?: string | null;
    imageSubcaption?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  propertyManagement: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    sectorsHeading?: string | null;
    body: string;
    checklist?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    cta?: string | null;
    image: number | Media;
    imageCaption?: string | null;
    imageSubcaption?: string | null;
  };
  outcomes: {
    eyebrow: string;
    heading?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    headingAccent?: string | null;
    body?: string | null;
    items?:
      | {
          /**
           * e.g. 01
           */
          index: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  accountability: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    headingTail?: string | null;
    body?: string | null;
    items?:
      | {
          /**
           * e.g. 01
           */
          index: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  whereWeOperate: {
    heading: string;
    headingAccent?: string | null;
    body?: string | null;
  };
  technology: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    headingTail?: string | null;
    body?: string | null;
    cta?: string | null;
    platforms?:
      | {
          name: string;
          tag?: string | null;
          description: string;
          highlighted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  cta: {
    eyebrow: string;
    heading: string;
    headingAccent?: string | null;
    headingTail?: string | null;
    body?: string | null;
    primaryCta?: string | null;
    secondaryCta?: string | null;
    stats?:
      | {
          value: string;
          label: string;
          highlighted?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Banner/intro only. Board members themselves live in the Board Members collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-board-page".
 */
export interface CompanyBoardPage {
  id: number;
  banner: number | Media;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  body?: string | null;
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Banner/intro only. Team members live in the Management Team collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-management-page".
 */
export interface CompanyManagementPage {
  id: number;
  banner: number | Media;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  body?: string | null;
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Banner/intro only. Articles live in the News Items collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-news-page".
 */
export interface CompanyNewsPage {
  id: number;
  banner: number | Media;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  body?: string | null;
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Banner/intro + M-Trainer platform features. Programs live in the Training Programs collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-training-page".
 */
export interface CompanyTrainingPage {
  id: number;
  banner: number | Media;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  body?: string | null;
  platformFeatures?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Banner/intro only. Jobs live in the Job Openings collection.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-current-openings-page".
 */
export interface CareerCurrentOpeningsPage {
  id: number;
  banner: number | Media;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  body?: string | null;
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-employee-benefits".
 */
export interface CareerEmployeeBenefit {
  id: number;
  banner: number | Media;
  eyebrow: string;
  heading: string;
  headingAccent?: string | null;
  body?: string | null;
  benefits?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Shown in browser tabs & search results. ~50-60 characters.
     */
    metaTitle?: string | null;
    /**
     * Shown in search results. ~150-160 characters.
     */
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  logoText?: T;
  logo?: T;
  parentBadge?: T;
  ctaLabel?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  badge?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              text?: T;
              id?: T;
            };
        headingAccent?: T;
        body?: T;
        primaryCta?: T;
        secondaryCta?: T;
        scrollLabel?: T;
        banner?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  about?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              text?: T;
              id?: T;
            };
        headingAccent?: T;
        body?: T;
        badges?:
          | T
          | {
              label?: T;
              id?: T;
            };
        facts?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        image?: T;
        imageCaption?: T;
      };
  verticals?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        body?: T;
        items?:
          | T
          | {
              index?: T;
              title?: T;
              description?: T;
              tags?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
            };
      };
  statsStrip?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  hardcoreRepair?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        body?: T;
        sectorsHeading?: T;
        checklist?:
          | T
          | {
              label?: T;
              id?: T;
            };
        cta?: T;
        image?: T;
        imageCaption?: T;
        imageSubcaption?: T;
      };
  corporateInterior?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        sectorsHeading?: T;
        body?: T;
        checklist?:
          | T
          | {
              label?: T;
              id?: T;
            };
        cta?: T;
        image?: T;
        imageCaption?: T;
        imageSubcaption?: T;
      };
  officeInterior?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        sectorsHeading?: T;
        body?: T;
        checklist?:
          | T
          | {
              label?: T;
              id?: T;
            };
        cta?: T;
        image?: T;
        imageCaption?: T;
        imageSubcaption?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  propertyManagement?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        sectorsHeading?: T;
        body?: T;
        checklist?:
          | T
          | {
              label?: T;
              id?: T;
            };
        cta?: T;
        image?: T;
        imageCaption?: T;
        imageSubcaption?: T;
      };
  outcomes?:
    | T
    | {
        eyebrow?: T;
        heading?:
          | T
          | {
              text?: T;
              id?: T;
            };
        headingAccent?: T;
        body?: T;
        items?:
          | T
          | {
              index?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  accountability?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        headingTail?: T;
        body?: T;
        items?:
          | T
          | {
              index?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  whereWeOperate?:
    | T
    | {
        heading?: T;
        headingAccent?: T;
        body?: T;
      };
  technology?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        headingTail?: T;
        body?: T;
        cta?: T;
        platforms?:
          | T
          | {
              name?: T;
              tag?: T;
              description?: T;
              highlighted?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        headingAccent?: T;
        headingTail?: T;
        body?: T;
        primaryCta?: T;
        secondaryCta?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              highlighted?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-board-page_select".
 */
export interface CompanyBoardPageSelect<T extends boolean = true> {
  banner?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-management-page_select".
 */
export interface CompanyManagementPageSelect<T extends boolean = true> {
  banner?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-news-page_select".
 */
export interface CompanyNewsPageSelect<T extends boolean = true> {
  banner?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-training-page_select".
 */
export interface CompanyTrainingPageSelect<T extends boolean = true> {
  banner?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  platformFeatures?:
    | T
    | {
        label?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-current-openings-page_select".
 */
export interface CareerCurrentOpeningsPageSelect<T extends boolean = true> {
  banner?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-employee-benefits_select".
 */
export interface CareerEmployeeBenefitsSelect<T extends boolean = true> {
  banner?: T;
  eyebrow?: T;
  heading?: T;
  headingAccent?: T;
  body?: T;
  benefits?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}